# Generated by Django 4.1 on 2022-08-30 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='titre',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
